[pytest]
# Default options:
# -n 2: Run tests in parallel with 2 workers
# -s: Disable output capture (so prints like device prices are shown in the console)
# -v: Verbose output format
addopts = -n 2 -s -v

# Directories to search for tests
testpaths = tests

# Configure logging
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S
